services:
  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: itt440
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  c_server:
    build: ./c_server
    depends_on:
      - mysql_db
    restart: unless-stopped

  c_client:
    build: ./c_client
    depends_on:
      - c_server

  py_server:
    build: ./py_server
    depends_on:
      - mysql_db
    restart: unless-stopped

  py_client:
    build: ./py_client
    depends_on:
      - py_server

  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    restart: unless-stopped